import { JobState } from "@/interfaces/job.interface"
import Logo from "../../public/icons/teams.svg"

export const profileStats = [
	{
		name: "Profile Visitors",
		value: 140,
	}, {
		name: "Resume Viewers",
		value: 20,
	}, {
		name: "My Jobs",
		value: 88
	}
]
export const locations = [
	"Remote",
	"New York",
	"San Francisco",
	"London",
	"Berlin",
	"Tokyo",
];
export const jobTypes = [
	"Full-time",
	"Part-time",
	"Contract",
	"Internship",
	"Temporary",
];

export const filterTags = [
	{ id: "frontend", label: "Frontend" },
	{ id: "backend", label: "Backend" },
	{ id: "graphic-designer", label: "Graphic Designer" },
]

// Initial job data
export const initialJobs: JobState = {
	promotedJobs: [
		{
			id: "1",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: true,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "2",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: true,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "3",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: true,
			logoUrl: Logo,
			isSaved: true,
		},
		{
			id: "4",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: true,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "5",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: true,
			logoUrl: Logo,
			isSaved: false,
		},
	],
	recommendedJobs: [
		{
			id: "6",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "7",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: true,
		},
		{
			id: "8",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "9",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "10",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "11",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "12",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "13",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "14",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "15",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
	],
	latestJobs: [
		{
			id: "16",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "17",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "18",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "19",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "20",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "21",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "22",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "23",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "24",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
		{
			id: "25",
			title: "UI/UX Designer",
			company: "Teams",
			location: "Seattle, USA",
			isRemote: true,
			postedAt: "2023-04-23",
			applicants: 22,
			isPromoted: false,
			logoUrl: Logo,
			isSaved: false,
		},
	],
}

